Mcloud4/urls.py
"""
Definition of urls for Mcloud4.
"""

from datetime import datetime
from django.conf.urls import patterns, url
from app.forms import BootstrapAuthenticationForm

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'app.views.home', name='home'),
    url(r'^contact$', 'app.views.contact', name='contact'),
    url(r'^about', 'app.views.about', name='about'),
    url(r'^login/$',
        'django.contrib.auth.views.login',
        {
            'template_name': 'app/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title':'Log in',
                'year':datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^T1LL/$', 'app.views.T1LL_input', name='T1LL_input'),
    url(r'^T1LL_result/$', 'app.views.T1LL_result', name='T1LL_result'),
    url(r'^Boston_fit/$', 'app.views.Boston_fit', name='Boston_fit'),
    url(r'^Boston_result/$', 'app.views.Boston_result', name='Boston_result'),
    url(r'^Iris/$', 'app.views.Iris', name='Iris'),
    url(r'^Iris_result/$', 'app.views.Iris_result', name='Iris_result'),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))


class BootstrapCurveFittingForm(forms.Form):
    """Fitting form for T1, T2  which uses boostrap CSS."""
    t_value = forms.CharField(label='t_value', max_length=254,widget=forms.TextInput(attrs={'size':'100'}))
    y_value = forms.CharField(label='y_value',max_length=254,widget=forms.TextInput(attrs={'size':'100'}))

    crim_value = forms.CharField(label='crim_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:88.9762 (0%~100%)'}))
    zn_value = forms.CharField(label='zn_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:100.0 (0%~100%)'}))
    indus_value = forms.CharField(label='indus_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:27.74 (0%~100%)'}))

    CHOICES=[('1','1 (if tract bounds river)'),('0','0 (otherwise)')]
    chas_value = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())
    #chas_value = forms.CharField(label='chas_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' '}))

    nox_value = forms.CharField(label='nox_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:0.871 (/10ppm)'}))
    rm_value = forms.CharField(label='rm_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:8.78'}))
    age_value = forms.CharField(label='age_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:100.0 (0%~100%)'}))
    dis_value = forms.CharField(label='dis_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:12.1265'}))
    rad_value = forms.CharField(label='rad_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:24.0'}))
    tax_value = forms.CharField(label='tax_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:711.0'}))
    ptratio_value = forms.CharField(label='ptratio_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:22.0'}))
    b_value = forms.CharField(label='b_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:396.9'}))
    lstat_value = forms.CharField(label='lstat_value',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' EX:37.97'}))

    sepal_length = forms.CharField(label='sepal_length',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' '}))
    sepal_width = forms.CharField(label='sepal_width',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' '}))
    petal_length = forms.CharField(label='petal_length',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' '}))
    petal_width = forms.CharField(label='petal_width',max_length=254,widget=forms.TextInput(attrs={'size':'100','placeholder':' '}))

app/templates/app/Iris_result.html
{% extends "app/layout.html" %}

{% block content %}

<div class="bs-callout bs-callout-primary">{{ HTML_text1 | safe}}</div>

<div class="bs-callout bs-callout-primary"><h4>Interactive Plot</h4>{{ plot1 | safe}} </div>

<div class="bs-callout bs-callout-primary"><h4>Paper-style Plot</h4>{{ plot2 | safe}} </div>

<div class="bs-callout bs-callout-info">{{ HTML_text2 | safe}} </div>


{% endblock %}

app/templates/app/WebPage1.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>

</body>
</html>

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

app/templates/app/boston_result.html
{% extends "app/layout.html" %}

{% block content %}

<div class="bs-callout bs-callout-primary">{{ HTML_text1 | safe}}</div>

<div class="bs-callout bs-callout-primary"><h4>Interactive Plot</h4>{{ plot1 | safe}} </div>

<div class="bs-callout bs-callout-primary"><h4>Paper-style Plot</h4>{{ plot2 | safe}} </div>

<div class="bs-callout bs-callout-info">{{ HTML_text2 | safe}} </div>


{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/app/fitting_input.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="/T1LL_result/" method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Fill in TI and SI to calculate T1</h4>
                <hr />
                <div class="form-group">
                    <label for="t_value" class="col-md-2 control-label">Times test</label>
                    <div class="col-md-10" >
                        {{ form.t_value }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_y_value" class="col-md-2 control-label">Signal Intensity</label>
                    <div class="col-md-10">
                        {{ form.y_value }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>



</div>

<p>
Try it!
<p>
Simply copy the following test data into the input boxes and click submit.
<p>

Test data:
<p>

TI= 120 220 370 1130 1168 1233 2115 2125 2145 3078 4035
<p>
SI= 114 87 56 75 80 89 137 132 128 151 168
<p>


<p>
Provided by Yi-Fu Tsai & Teng-Yi Huang
{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/fitting_input1.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="{% url 'Boston_result' %}" method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Fill in features to predict the prices.</h4>
                <hr />
                <div class="form-group">
                    <label for="crim_value" class="col-md-2 control-label" style="font-size:150%">CRIM</label>
                    <div class="col-md-10" ><i style="color:gray">per capita crime rate by town</i><br>
                      {{ form.crim_value }}</div>
                </div>
                <div class="form-group">
                    <label for="zn_value" class="col-md-2 control-label" style="font-size:150%">ZN</label>
                    <div class="col-md-10"><i style="color:gray">proportion of residential land zoned for lots over 25,000 sq.ft.</i><br>
                      {{ form.zn_value }}</div>
                </div>
                <div class="form-group">
                    <label for="indus_value" class="col-md-2 control-label" style="font-size:150%">INDUS</label>
                    <div class="col-md-10"><i style="color:gray">proportion of non-retail business acres per town</i><br>
                      {{ form.indus_value }}</div>
                </div>
                <div class="form-group">
                    <label for="chas_value" class="col-md-2 control-label" style="font-size:150%">CHAS</label>
                    <div class="col-md-10"><i style="color:gray">Charles River dummy variable</i><br>
                      {{ form.chas_value }}</div>
                </div>
                <div class="form-group">
                    <label for="nox_value" class="col-md-2 control-label" style="font-size:150%">NOX</label>
                    <div class="col-md-10"><i style="color:gray">nitric oxides concentration (parts per 10 million)</i><br>
                      {{ form.nox_value }}</div>
                </div>
                <div class="form-group">
                    <label for="rm_value" class="col-md-2 control-label" style="font-size:150%">RM</label>
                    <div class="col-md-10"><i style="color:gray">average number of rooms per dwelling</i><br>
                      {{ form.rm_value }}</div>
                </div>
                <div class="form-group">
                    <label for="age_value" class="col-md-2 control-label" style="font-size:150%">AGE</label>
                    <div class="col-md-10"><i style="color:gray">proportion of owner-occupied units built prior to 1940</i><br>
                      {{ form.age_value }}</div>
                </div>
                <div class="form-group">
                    <label for="dis_value" class="col-md-2 control-label" style="font-size:150%">DIS</label>
                    <div class="col-md-10"><i style="color:gray">weighted distances to five Boston employment centres</i><br>
                      {{ form.dis_value }}</div>
                </div>
                <div class="form-group">
                    <label for="rad_value" class="col-md-2 control-label" style="font-size:150%">RAD</label>
                    <div class="col-md-10"><i style="color:gray">index of accessibility to radial highways</i><br>
                      {{ form.rad_value }}</div>
                </div>
                <div class="form-group">
                    <label for="tax_value" class="col-md-2 control-label" style="font-size:150%">TAX</label>
                    <div class="col-md-10"><i style="color:gray">full-value property-tax rate per $10,000</i><br>
                      {{ form.tax_value }}</div>
                </div>
                <div class="form-group">
                    <label for="ptratio_value" class="col-md-2 control-label" style="font-size:150%">PTRATIO</label>
                    <div class="col-md-10"><i style="color:gray">pupil-teacher ratio by town</i><br>
                      {{ form.ptratio_value }}</div>
                </div>
                <div class="form-group">
                    <label for="b_value" class="col-md-2 control-label" style="font-size:150%">B</label>
                    <div class="col-md-10"><i style="color:gray">1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town</i><br>
                      {{ form.b_value }}</div>
                </div>
                <div class="form-group">
                    <label for="lstat_value" class="col-md-2 control-label" style="font-size:150%">LSTAT</label>
                    <div class="col-md-10"><i style="color:gray">% lower status of the population</i><br>
                      {{ form.lstat_value }}</div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Submit" class="btn btn-default"  style="font-size:125%"/>
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>



</div>

<p>
Try it!
<p>
Simply copy the following test data into the input boxes and click submit.
<p>

Test data:
<p>
feature_names = [CRIM, ZN, INDUS, CHAS, NOX, RM, AGE, DIS, RAD, TAX, PTRATIO, B, LSTAT]

<p>
data = [0.00632, 18, 2.31 ,0 ,0.538 ,6.575, 65.2, 4.09, 1, 296, 15.3, 396.9, 4.98]
<p>


<p>
Provided by Yun-Wen Wang & Teng-Yi Huang
{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/fitting_input2.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="{% url 'Iris_result' %}" method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Fill in features to predict the types of flowers.</h4>
                <hr />
                <div class="form-group">
                    <label for="sepal_length" class="col-md-2 control-label">sepal length (cm)</label>
                    <div class="col-md-10" >
                      {{ form.sepal_length }}</div>
                </div>
                <div class="form-group">
                    <label for="sepal_width" class="col-md-2 control-label">sepal width (cm)</label>
                    <div class="col-md-10">
                      {{ form.sepal_width }}</div>
                </div>
                <div class="form-group">
                    <label for="petal_length" class="col-md-2 control-label">petal length (cm)</label>
                    <div class="col-md-10">
                      {{ form.petal_length }}</div>
                </div>
                <div class="form-group">
                    <label for="petal_width" class="col-md-2 control-label">petal width (cm)</label>
                    <div class="col-md-10">
                      {{ form.petal_width }}</div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Submit" class="btn btn-default"  style="font-size:125%"/>
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>



</div>

<p>
Try it!
<p>
Simply copy the following test data into the input boxes and click submit.
<p>

Test data:
<p>
feature_names = [sepal_length,sepal_width,petal_length,petal_width]

<p>
data = []
<p>


<p>
Provided by Yun-Wen Wang & Teng-Yi Huang
{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/fitting_plotJS - Copy.html
{% extends "app/layout.html" %}

{% block content %}

<div class="bs-callout bs-callout-primary">{{ HTML_text1 | safe}}</div>



<script type="text/javascript">
        $(function () {
            $('#container').highcharts({

                    credits: {
            text: '',
            href: 'http://cloud.mrilab.org'
        },
                chart: {
                    type: 'scatter',
                    zoomType: 'xy'
                },
                title: {
                    text: '{{ chart_title}}'
                },
           
                xAxis: {
                    title: {
                        enabled: true,
                        text: '{{ xAxis_label}}'
                    },
                    startOnTick: true,
                    endOnTick: true,
                    showLastLabel: true
                },
                yAxis: {
                    title: {
                        text: '{{ yAxis_label}}'
                    }
                },
                legend: {
                    layout: 'vertical',
                    align: 'left',
                    verticalAlign: 'top',
                    x: 100,
                    y: 70,
                    floating: true,
                    backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF',
                    borderWidth: 1
                },
                plotOptions: {
                    scatter: {
                        marker: {
                            radius: 5,
                            states: {
                                hover: {
                                    enabled: true,
                                    lineColor: 'rgb(100,100,100)'
                                }
                            }
                        },
                        states: {
                            hover: {
                                marker: {
                                    enabled: false
                                }
                            }
                        },
                        tooltip: {
                            headerFormat: '<b>{series.name}</b><br>',
                            pointFormat: '{point.x} ms, {point.y} '
                        }
                    }
                },
                series: [{
                    name: 'Original',
                    color: 'rgba(223, 83, 83, .8)',
        			
                    data: [	{{ original_data}}	]
        
                }, {
                    name: 'Fitted Data',
        			lineWidth: 3,
        			 marker: {
                                    enabled: false
                                },
                    color: 'rgba(119, 152, 191, 1)',
                    data: [	{{ fitted_data}}	]
                }]
            });
        });
            
        
</script>

<div class="bs-callout bs-callout-primary"><h4>Interactive Plot</h4><div id="container" style="width: 80%; height: 480px; margin: 0 auto;"></div></div>




<div class="bs-callout bs-callout-primary"><h4>Paper-style Plot</h4>{{ SVG | safe}} </div>


<div class="bs-callout bs-callout-info">
{{ HTML_text2 | safe}}
Provided by Yi-Fu Tsai & Teng-Yi Huang
    </div> 





{% endblock %}

app/templates/app/fitting_result.html
{% extends "app/layout.html" %}

{% block content %}

<div class="bs-callout bs-callout-primary">{{ HTML_text1 | safe}}</div>



<div class="bs-callout bs-callout-primary"><h4>Interactive Plot</h4>{{ highchart | safe}} </div>




<div class="bs-callout bs-callout-primary"><h4>Paper-style Plot</h4>{{ SVG | safe}} </div>


<div class="bs-callout bs-callout-info">
{{ HTML_text2 | safe}}
<H4>Provided by Yi-Fu Tsai & Teng-Yi Huang</H4>
    </div> 





{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>MR Fitting</h1>
    <p class="lead">MR Fitting is a web framework for curve fitting for time series obtained in MR experiments.</p>
    <p><a href="#" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Django gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>The Python Package Index is a repository of software for the Python programming language.</p>
        <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Microsoft Azure</h2>
        <p>You can easily publish to Microsoft Azure using Python Tools for Visual Studio. Find out how you can host your application using a free trial today.</p>
        <p><a class="btn btn-default" href="#">Learn more &raquo;</a></p>
    </div>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
     <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>

    <script type="text/x-mathjax-config">
     MathJax.Hub.Config({tex2jax: {inlineMath: [['$$','$$'], ['\\(','\\)']]},SVG: { scale: 150 },  displayAlign: 'left'});
    </script>
    <script type="text/javascript"
    src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>
    <style type="text/css">
        ${demo.css}
    </style>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">MR fitting</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
<!--                <li><a href="{% url 'T1LL_input' %}">T1 (Look-Locker)</a></li>
                    <li><a href="{% url 'Boston_fit' %}">Boston</a></li>
-->
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-    haspopup="true" aria-expanded="false">Calculation <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'T1LL_input' %}">T1 (Look-Locker)</a></li>
                            <li><a href="{% url 'Boston_fit' %}">Boston</a></li>
                            <li><a href="{% url 'Iris' %}">Iris</a></li>
                        </ul>
                    </li>
                </ul>

                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Cloud.MR</p>
        </footer>
    </div>


    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
            <script src='/static/js/highcharts.js'></script>
        <script src='/static/js/modules/exporting.js'></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}